spring:
  application:
    name: zuul
server:
  port: 8765
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    #   # client-auth: need
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
  #     trust-store: classpath:zuul.jks
  #     trust-store-password: zuul123

eureka:
  instance:
    hostname: localhost
    securePort: 8761
    securePortEnabled: true
    prefer-ip-address: true
    nonSecurePortEnabled: false
    statusPageUrl: https://${eureka.instance.hostName}:${eureka.instance.securePort}/info
    healthCheckUrl: https://${eureka.instance.hostName}:${eureka.instance.securePort}/health
    homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${eureka.instance.securePort}/eureka

zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  host:
    connect-timeout-millis: 5000000
    # socket-timeout-millis: 5000000
  # retryable: true
  sslHostnameValidationEnabled: false
  # okhttp:
  #   enabled: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
