spring:
  application:
    name: issuer
server:
  port: 8035
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    #   # client-auth: need
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
#     trust-store: classpath:issuerks
#     trust-store-password: issuer

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
