spring:
  application:
    name: bitcoin
server:
  port: 8006
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    #   # client-auth: need
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
#     trust-store: classpath:bitcoin.jks
#     trust-store-password: bitcoin

eureka:
  instance:
    hostname: localhost
    securePort: 8761
    securePortEnabled: true
    prefer-ip-address: true
    nonSecurePortEnabled: false
    statusPageUrl: https://${eureka.instance.hostName}:${eureka.instance.securePort}/info
    healthCheckUrl: https://${eureka.instance.hostName}:${eureka.instance.securePort}/health
    homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${eureka.instance.securePort}/eureka

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

coingate:
  url: https://api-sandbox.coingate.com/v2
  token: guYqAtDARCitszy7qFTgqmRwKiHJWUSqbwLWy1u7
