spring:
  application:
    name: sellers
server:
  port: 8003
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    #   # client-auth: need
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
  #   trust-store: classpath:sellers.jks
  #   trust-store-password: sellers

eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    # preferIpAddress: true
    nonSecurePortEnabled: false
    # statusPageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/info
    # healthCheckUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/health
    # homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}
  client:
    registerWithEureka: true
    fetchRegistry: false
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:8761/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
