spring:
  application:
    name: nc
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_nc?createDatabaseIfNotExist=true
    username: root
    password: tanja
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8080
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    #   # client-auth: need
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
#     trust-store: classpath:acquirer.jks
#     trust-store-password: acquirer
# security:
#   require-ssl: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

client:
  url: https://localhost:4200/
kp:
  url: https://localhost:8765/
