spring:
  application:
    name: paypal
server:
  port: 8007
  ssl:
    enabled: true
    enabled-protocols: TLSv1.2
    #   # client-auth: need
    key-store: classpath:localhost.p12
    key-store-password: changeit
    key-store-type: PKCS12
#     trust-store: classpath:paypal.jks
#     trust-store-password: paypal

eureka:
  instance:
    hostname: localhost
    securePort: 8761
    securePortEnabled: true
    # preferIpAddress: true
    nonSecurePortEnabled: false
    statusPageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/info
    healthCheckUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}/health
    homePageUrl: https://${eureka.instance.hostname}:${eureka.instance.securePort}
  client:
    registerWithEureka: true
    fetchRegistry: false
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:8761/eureka/

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

paypal:
  access-token: A21AAF8N319okIBmgbMmCmUMZeAvoazmEGzTlpvHjTBxxRhS9Idg-QMRveygJnOVCHWBQk9db-KarZ37XObd24AHoRU76l89Q
