spring:
  application:
    name: paypal
server:
  port: 8007
  ssl:
    enabled: true
    key-store: classpath:paypal.jks
    key-store-password: paypal
    key-alias: paypal
    trust-store: classpath:paypal.jks
    trust-store-password: paypal
security:
  require-ssl: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
  client:
    securePortEnabled: true
    serviceUrl:
      defaultZone: https://localhost:8761/eureka/
# ribbon:
#   IsSecured: true
#   ConnectTimeout:  10000
#   ReadTimeout:  10000
#   eureka:
#     enabled: true
#   TrustStore: classpath:paypal.jks
#   TrustStorePassword : paypal
#   IsHostnameValidationRequired: false